### ISSUE TITLE
Add '3rd party app required' to Pick'N'Pay locations

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#6219]
## Context 

We recently added support for the following tags in the Web App.

`payment:lightning:companion_app_url`
`payment:lightning:requires_companion_app`

This was initially to support Qerko (mainly in the Czech Republic), but this needs to be applied to other merchants that accept Bitcoin with the support of a companion app, like [CryptoConvert](https://www.cryptoconvert.co.za/#app)

Example here:

https://btcmap.org/merchant/node:11036283304

## Task

Update the Pick'N'Pay locations to:

- [ ] Remove any `payment:lightning`, `payment:lightning_contactless` or `payment:onchain` tags
- [ ] Add `payment:lightning:requires_companion_app=yes`
- [ ] Add `payment:lightning:companion_app_url=https://www.cryptoconvert.co.za/#app`

## Background

Issue #2409 covers the initial import, including liaison with the local OSM community. Discussion [here](https://community.openstreetmap.org/t/pick-n-pay-stores-bitcoin/8771).

**Comment by dadofsambonzuki** [comment]
I handled the initial comms with the local mods and so I'll pick-up the old thread.
